// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrO6lltcc-CwbuqZm2TQVoZkDZ2j_lLuw',
    appId: '1:636289331063:web:bc6bccc12d987bb2f47b72',
    messagingSenderId: '636289331063',
    projectId: 'gdsstudytest',
    authDomain: 'gdsstudytest.firebaseapp.com',
    storageBucket: 'gdsstudytest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu5sZGx7c8LWCeVnouY7SWQDYVsord3Vo',
    appId: '1:636289331063:android:1287f6d2202a6b5df47b72',
    messagingSenderId: '636289331063',
    projectId: 'gdsstudytest',
    storageBucket: 'gdsstudytest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa_gl96kDyQQG0drU9QQXrkPde46aYIdU',
    appId: '1:636289331063:ios:4864c38d54842ab8f47b72',
    messagingSenderId: '636289331063',
    projectId: 'gdsstudytest',
    storageBucket: 'gdsstudytest.firebasestorage.app',
    iosBundleId: 'com.example.gdsstudytest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa_gl96kDyQQG0drU9QQXrkPde46aYIdU',
    appId: '1:636289331063:ios:4864c38d54842ab8f47b72',
    messagingSenderId: '636289331063',
    projectId: 'gdsstudytest',
    storageBucket: 'gdsstudytest.firebasestorage.app',
    iosBundleId: 'com.example.gdsstudytest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrO6lltcc-CwbuqZm2TQVoZkDZ2j_lLuw',
    appId: '1:636289331063:web:3ea5d10e95a6eae4f47b72',
    messagingSenderId: '636289331063',
    projectId: 'gdsstudytest',
    authDomain: 'gdsstudytest.firebaseapp.com',
    storageBucket: 'gdsstudytest.firebasestorage.app',
  );
}
