// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKFdIBtDZFnJIuFX0DFKmSlmjJviDnf7M',
    appId: '1:831745302528:web:315ae4b9e4730b09dcb8e5',
    messagingSenderId: '831745302528',
    projectId: 'gdgstudy-44e0b',
    authDomain: 'gdgstudy-44e0b.firebaseapp.com',
    storageBucket: 'gdgstudy-44e0b.firebasestorage.app',
    measurementId: 'G-X9HHZRVQ8E',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjVax6geNa4Om-s_JM1fc8cX-YzmPOHf4',
    appId: '1:831745302528:ios:8dd6bada1601bcc1dcb8e5',
    messagingSenderId: '831745302528',
    projectId: 'gdgstudy-44e0b',
    storageBucket: 'gdgstudy-44e0b.firebasestorage.app',
    iosBundleId: 'com.example.gdgstudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjVax6geNa4Om-s_JM1fc8cX-YzmPOHf4',
    appId: '1:831745302528:ios:8dd6bada1601bcc1dcb8e5',
    messagingSenderId: '831745302528',
    projectId: 'gdgstudy-44e0b',
    storageBucket: 'gdgstudy-44e0b.firebasestorage.app',
    iosBundleId: 'com.example.gdgstudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKFdIBtDZFnJIuFX0DFKmSlmjJviDnf7M',
    appId: '1:831745302528:web:36a7de9829bded46dcb8e5',
    messagingSenderId: '831745302528',
    projectId: 'gdgstudy-44e0b',
    authDomain: 'gdgstudy-44e0b.firebaseapp.com',
    storageBucket: 'gdgstudy-44e0b.firebasestorage.app',
    measurementId: 'G-V14BVS3ZVE',
  );
}
